- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible') }}"

- name: upper value
  hosts: localhost
  vars:
    mess: "greetings"
  tasks:
  - name: print upper case
    ansible.builtin.debug:
      msg: "hello {{ mess | upper }}"

- name: lower value
  hosts: localhost
  vars:
    mess: "GREETINGS"
  tasks:
  - name: print lower case
    ansible.builtin.debug:
      msg: "Hello {{ mess | lower }}"

- name: numbers
  hosts: localhost  
  vars:
    numbers: [1, 2, 3, 4, 5, 6, 6]
  tasks:
  - name: to print unique numbers
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: min and max ages
  hosts: local host
  vars:
    ages: [23, 45, 67, 65, 32]
  tasks:
  - name: To print min and max ages
    ansible.builtin.debug:
      msg: "Min age is {{ ages | min }} and Max age is {{ ages | max }}"


