- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible') }}"

- name: upper value
  hosts: localhost
  vars:
    mess: "greetings"
  tasks:
  - name: print upper case
    ansible.builtin.debug:
      msg: "hello {{ mess | upper }}"