- name: install and start nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      state: installed
  - name: started nginx
    ansible.builtin.service:
      state: started
      enabled: yes


