- name: install and start nginx
  hosts: web
  become: yes
  tasks:
   - name: nginx
     ansible.builtin.dnf:
      name: nginx
      state: installed
   - ansible.builtin.service:
      state: started
      enabled: yes


