- name: install and start nginx
  hosts: web
  become: yes
  tasks:
    ansible.builtin.dnf:
      name: nginx
      state: installed
    ansible.builtin.service:
      state: started
      enabled: yes


