- name: variables
  hosts: localhost
  vars: 
    Course: "Ansible"
    Trainer: "Sivakumar"
    Duration: "3months"
  tasks:
  - name: To print override information
    vars:
      Course: "Devops"
      Trainer: "Vivek"
    ansible.builtin.debug:
      msg: "Hi, I am learining {{Course}}, and the tariner is {{Trainer}} course duration is {{Duration}}"

  - name: To print information
    ansible.builtin.debug:
      msg: "Hi, I am learining {{Course}}, and the tariner is {{Trainer}} course duration is {{Duration}}"