- name: variables
  hosts: localhost
  vari: 
    Course: "Ansible"
    Trainer: "Sivakumar"
    Duration: "3months"
  tasks:
  - name: To print information
    vari:
      Course: "Devops"
      Trainer: "Vivek"
      Duration: "1-month"
    ansible.builtin.debug:
      msg: "Hi, I am learining {{Course}}, and the tariner is {{Trainer}} course duration is {{Duration}}"

  - name: To print informatio
    ansible.builtin.debug:
      msg: "Hi, I am learining {{Course}}, and the tariner is {{Trainer}} course duration is {{Duration}}"